image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 8888   # default init was 3000
    onOpen: open-browser
  - port: 3999
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - before: git config --global user.email $GIT_COMMITTER_EMAIL
    init: pipenv install --dev && pipenv run jupyter lab build
    # Note: don't use pipenv shell in prebuild. Since it never ends, neither does prebuild
    prebuild: pipenv run echo "prebuild script ran"
    # Note: if starting the pipenv shell, it must be the last command in the script
    # Use `pipenv run` for shell commands prior to interactive mode
    command: pipenv shell


###################
# Debug artifacts #
###################

#  - before: BREADCRUMB=$BREADCRUMB" before" && export EXP_BREADCRUMB=$EXP_BREADCRUMB" before" && echo "$BREADCRUMB $GP_CONDA_ENV" && echo "$BREADCRUMB $GP_CONDA_ENV"
#    init: BREADCRUMB=$BREADCRUMB" init" && export EXP_BREADCRUMB=$EXP_BREADCRUMB" init" && echo "$BREADCRUMB $GP_CONDA_ENV" && echo "$BREADCRUMB $GP_CONDA_ENV"
#    command: BREADCRUMB=$BREADCRUMB" command" && export EXP_BREADCRUMB=$EXP_BREADCRUMB" command" && echo "$BREADCRUMB $GP_CONDA_ENV" && echo "$BREADCRUMB $GP_CONDA_ENV"
#    prebuild: BREADCRUMB=$BREADCRUMB" prebuild" && export EXP_BREADCRUMB=$EXP_BREADCRUMB" prebuild" && echo "$BREADCRUMB $GP_CONDA_ENV" && echo "$BREADCRUMB $GP_CONDA_ENV"

#  - before: echo "before env= $GIT_COMMITTER_EMAIL" >> /workspace/boot.log
#  - init: echo "init env= $GIT_COMMITTER_EMAIL" >> /workspace/boot.log
#  - command: echo "command env= $GIT_COMMITTER_EMAIL" >> /workspace/boot.log
#  - prebuild: echo "prebuild env= $GIT_COMMITTER_EMAIL" >> /workspace/boot.log
